#ifndef __BF_DICT_H__
#define __BF_DICT_H__

#include "BL_Tools.h"
#include <Catalog.h>


#define BF_DICT_VOLUMEDIALOG_TITLE	"Select volume"
#define BF_DICT_TOPMENU_LEFT	"Left"
#define BF_DICT_TOPMENU_COMMON_SAVE_PALETTE	"Save palette"
#define BF_DICT_FILES_FROM 	" from "
#define BF_DICT_FILES_PATHHIST_EMPTY	"sorry, but path_history is empty"
#define BF_DICT_WARNING	"Warning"
#define BF_DICT_FILES_MKLINK	"MkLink"
#define BF_DICT_RENAME	"Rename"
#define BF_DICT_FILES_TOVOID	"To void"
#define BF_DICT_VIEW	"View"
#define BF_DICT_EDIT	"Edit"
#define BF_DICT_COPY	"Copy"
#define BF_DICT_MOVE	"Move"
#define BF_DICT_TOPMENU_COMMON_LOAD_PALETTE	"Load palette"
#define BF_DICT_FILES_MKDIR	"MkDir"
#define BF_DICT_FILES_TOTRASH 	"To trash"
#define BF_DICT_FILES_MKFOLDEMPTY	"I can`t make folder with empty name"
#define BF_DICT_FILES_VOLREAD	"Are you crazy ? This volume is READ_ONLY !"
#define BF_DICT_FILES_ERRMKDIR	"Error while MakeDir"
#define BF_DICT_FILES_TOLOWER	"To lower"
#define BF_DICT_FILES_TOUPPER	"To upper"
#define BF_DICT_FILES_CAPITALISE	"Capitalise"
#define BF_DICT_FILES_CAPITALISEEW	"Capitalise EW"
#define BF_DICT_FILES_CHANGENAMES	"Change file names"
#define BF_DICT_TOPMENU_COMMON_ABOUT	"About..."
#define BF_DICT_FILES_MKLINKS	"Make links to"
#define BF_DICT_PATH	"Path"
#define BF_DICT_PANEL_DIR	"<dir>"
#define BF_DICT_PANEL_FILEEMPTYNAME	"Are you crazy? File can`t has empty name"
#define BF_DICT_PANEL_SEL_INVERT	"Invert selection"
#define BF_DICT_PANEL_SEL_SET	"Set selection"
#define BF_DICT_PANEL_SEL_UNSET	"Unset selection"
#define BF_DICT_PANEL_MASK	"Mask"
#define BF_DICT_PANEL_FOLDERALSO	"Folder also"
#define BF_DICT_PANEL_SETUP	"Panel setup"
#define BF_DICT_TOPMENU_COMMON_QUIT	"Quit"
#define BF_DICT_PANEL_SHOWICONS	"Show icons"
#define BF_DICT_PANEL_SHOWDATES	"Show dates"
#define BF_DICT_PANEL_SHOWSIZES	"Show sizes"
#define BF_DICT_PANEL_SHOWTYPES	"Show types"
#define BF_DICT_COPYTO	"Copy to"
#define BF_DICT_SPECIAL	"Special"
#define BF_DICT_MOVETO	"Move to"
#define BF_DICT_QUESTIONS	"Question"
#define BF_DICT_PANEL_DELETEFILES	"Delete files?"
#define BF_DICT_PANEL_PANELEMPTY	"Sorry, but panel is empty"
#define BF_DICT_OK	"Ok"
#define BF_DICT_PANEL_FROM	"From"
#define BF_DICT_PANEL_TO	"To"
#define BF_DICT_SETUPCOLOR_PANELFRAME	"Panel : Frame"
#define BF_DICT_SETUPCOLOR_PANELNODE	"Panel : Node"
#define BF_DICT_SETUPCOLOR_PANELNODELINK	"Panel : Node : Link"
#define BF_DICT_SETUPCOLOR_PANELNODEDIR 	"Panel : Node : Dir"
#define BF_DICT_SETUPCOLOR_PANELNODEDIRLINK	"Panel : Node : Dir : Link"
#define BF_DICT_SETUPCOLOR_PANELINFOTEXT 	"Panel : Info : Text"
#define BF_DICT_SETUPCOLOR_PANELCURSORBACK	"Panel : Cursor : Back"
#define BF_DICT_SETUPCOLOR_PANELCURSORTEXT	"Panel : Cursor : Text"
#define BF_DICT_CANCEL	"Cancel"
#define BF_DICT_SETUPCOLOR_PANELHEADERSTEXT	"Panel : Headers : Text"
#define BF_DICT_SETUPCOLOR_PANELFOCUSPATHTEXT 	"Panel : FocusPath :  Text"
#define BF_DICT_SETUPCOLOR_PANELFOCUSPATHBACK	"Panel : FocusPath :  Back"
#define BF_DICT_SETUPCOLOR_PANELPATHTEXT	"Panel : Path : Text"
#define BF_DICT_SETUPCOLOR_PANELNODESELECTING	"Panel : Node : Selecting"
#define BF_DICT_SETUPCOLOR_PANELNODEFOCUSSELECTING	"Panel : Node : Focus&Selecting"
#define BF_DICT_SETUPCOLOR_DIALOGFOCUSEDBORDER   	"Dialog : FocusedBorder"
#define BF_DICT_SETUPCOLOR_DIALOGUNFOCUSEDBAR	"Dialog : UnfocusedBorder"
#define BF_DICT_SETUPCOLOR_DIALOGBACK	"Dialog : Back"
#define BF_DICT_SETUPCOLOR_DIALOGTEXT	"Dialog : Text"
#define BF_DICT_YES	"Yes"
#define BF_DICT_SETUPCOLOR_DIALOGMENU	"Dialog : Menu : Item selected"
#define BF_DICT_SETUPCOLOR_DIALOGEDITTEXT	"Dialog : Edit : Text"
#define BF_DICT_SETUPCOLOR_DIALOGEDITBACK	"Dialog : Edit : Back"
#define BF_DICT_SETUPCOLOR_DIALOGBUTTONFOCUS	"Dialog : Button : Focus"
#define BF_DICT_SETUPCOLOR_DIALOGBUTTONTEXT	"Dialog : Button : Text"
#define BF_DICT_SETUPCOLOR_DIALOGPROGRESSBARE	"Dialog : ProgressBar : Empty"
#define BF_DICT_SETUPCOLOR_DIALOGPROGRESSBARF	"Dialog : ProgressBar : Filled"
#define BF_DICT_SETUPCOLOR_DIALOGRED	"Red"
#define BF_DICT_SETUPCOLOR_COMMANDLINE_BACK	"CommandLine : Back"
#define BF_DICT_SETUPCOLOR_COMMANDLINE_TEXT	"CommandLine : Text"
#define BF_DICT_NO	"No"
#define BF_DICT_SETUPCOLOR_TEXTVIEWER1	"TextViewer : Status bar : text"
#define BF_DICT_SETUPCOLOR_TEXTVIEWER2	"TextViewer : Status bar : back"
#define BF_DICT_SETUPCOLOR_TEXTVIEWER3	"TextViewer : Text"
#define BF_DICT_SETUPCOLOR_TEXTVIEWER4	"TextViewer : Background : back"
#define BF_DICT_SETUP_ERR2	"can`t make settings dir"
#define BF_DICT_SETUP_ERR3	"can`t create setting_file,error : "
#define BF_DICT_SETUP_ERR4	"can`t load palete_file,error : "
#define BF_DICT_SETUP_ERR5	"can`t create palete_file,error : "
#define BF_DICT_SETUPCOLOR_PANELPATHBACK	"Panel : Path : Back"
#define BF_DICT_MENU_SORTNAME	"Sort by name"
#define BF_DICT_PANEL_CREATEFOLDER_TITLE	"Create folder"
#define BF_DICT_SETUP_ERR1	"can`t create file vars.settings,error : "
#define BF_DICT_SETUPCOLOR_PANELBACK	"Panel : Back"
#define BF_DICT_PATH_EMPTY	"command`s history is empty"
#define BF_DICT_PATH_CANNOTRUN	"can`t run this command"
#define BF_DICT_FILES_CANTRUN	"I can`t run this file"
#define BF_DICT_FILES_MKSHLINK	"Make SH-link"
#define BF_DICT_TARGETFILE	"Target file"
#define BF_DICT_SCRIPTNAME	"Script name"
#define BF_DICT_INFOLDER	"In folder"
#define BF_DICT_MENU_SORTSIZE	"Sort by size"
#define BF_DICT_ARGS	"Arguments"
#define BF_DICT_FILES_MKSHLINK_SETICONS	"Set icons from source file"
#define BF_DICT_FILES_MKSH_ERROR1	"Error while folder opening"
#define BF_DICT_FILES_MKSH_ERROR2	"Store folder not found"
#define BF_DICT_FILES_MKSH_ERROR3	"This file exists"
#define BF_DICT_FILES_MKSH_ERROR4	"Write permission request denied"
#define BF_DICT_FILES_MKSH_ERROR5	"Error while file creating"
#define BF_DICT_INFOPANEL_TITLE	"File information"
#define BF_DICT_INFOPANEL_SIZE	"Size: "
#define BF_DICT_TOPMENU_COMMON	"Common"
#define BF_DICT_MENU_SORTDATE	"Sort by date"
#define BF_DICT_INFOPANEL_DATE	"Date: "
#define BF_DICT_INFOPANEL_PERMS	"Perms: "
#define BF_DICT_INFOPANEL_CAPACITY	"Capacity: "
#define BF_DICT_INFOPANEL_MIME	"MIME: "
#define BF_DICT_INFOPANEL_FREEBYTES	"Free bytes : "
#define BF_DICT_INFOPANEL_REMOVEABLE	"Removeable "
#define BF_DICT_READONLY	"Read only"
#define BF_DICT_CANTLOADINFO	"Can`t load info"
#define BF_DICT_TASKS_READONLYVOL	"Are you crazy ? This volume is READ_ONLY !"
#define BF_DICT_TASKS_ONENAMEMANYFILES	"Sorry, but I can`t give one name to many files "
#define BF_DICT_TASKS_DESTFOLDERNAMEWRONG	"Are you crazy ? Name of dest.folder is wrong"
#define BF_DICT_MENU_SORTTYPE	"Sort by type"
#define BF_DICT_TASKS_CREATEITNOW	"Create it now!"
#define BF_DICT_TASKS_DESTFOLDERNOTEXIST	"Dest.folder is not existing"
#define BF_DICT_TASKS_CANTMAKEFOLDER	"Sorry,i can`t make folder"
#define BF_DICT_TASKS_DESTVOLREADONLY	"Are you crazy ? Destination volume is READ_ONLY !"
#define BF_DICT_TASKS_CANTMAKETRASH	"can`t make Trash_Dir "
#define BF_DICT_SKIP	"Skip"
#define BF_DICT_TRYAGAIN	"Try again"
#define BF_DICT_TASKS_SYSFOLDERDELETE	"This is a system folder. Do you really want to delete it ?"
#define BF_DICT_TASKS_COPYINGFILES	"copying files"
#define BF_DICT_TASKS_COPYINGFILESFROM	"copying files from /"
#define BF_DICT_MENU_SORTEXT	"Sort by ext"
#define BF_DICT_TASKS_COPYINGFILESTO	" to /"
#define BF_DICT_TASKS_DESTFILE	"Dest.file "
#define BF_DICT_TASKS_DESTFILEEXIST	" is existing"
#define BF_DICT_OWERWRITE	"Owerwrite"
#define BF_DICT_CANCELALL	"Cancel all"
#define BF_DICT_TASKS_CANTMOVE	" Can`t move file "
#define BF_DICT_TASKS_CANTMAKERENAME	"Sorry, but I can`t make links and rename them at one time."
#define BF_DICT_TASKS_CANTMAKEINFOLDER	"Sorry, but I can`t make all links with one name"
#define BF_DICT_TASKS_CANTMAKELINKONENAME	"Sorry, but I can`t make links in folder"
#define BF_DICT_TASKS_EXISTSSKIPASK	" exists. Skip it ?"
#define BF_DICT_TRADDS_NONE	"can`t find any tracker add-ons"
#define BF_DICT_MENU_SHOWHIDE_ICONS	"Show/Hide icons"
#define BF_DICT_CREATE	"Create"
#define BF_DICT_DELETE	"Delete"
#define BF_DICT_FTP_DISCONNECT	"Disconnect"
#define BF_DICT_FTP_MAKEDIR	"MakeDir"
#define BF_DICT_FTP_CONNECTED	"Ftp:Connected"
#define BF_DICT_FTP_ERROR	"ftp error"
#define BF_DICT_FTP_EDITBKM	"Edit bookmark"
#define BF_DICT_FTP_BKM_TITLE	"Title:"
#define BF_DICT_FTP_BKM_HOST	"Host:"
#define BF_DICT_MENU_FULLMODE	"Full mode"
#define BF_DICT_FTP_BKM_USERNAME	"User name:"
#define BF_DICT_FTP_BKM_PWD	"Password:"
#define BF_DICT_FTP_BKM_FOLDER	"Folder:"
#define BF_DICT_FTP_PANELTITLE	"Ftp bookmarks"
#define BF_DICT_FTP_CANTMAKESETDIR	"can`t make settings dir"
#define BF_DICT_FTP_CANTMAKESETFILE	"can`t make setting_file "
#define BF_DICT_FTP_CONNECTING	"Ftp:Connecting..."
#define BF_DICT_FTP_DIRCHANGING	"Ftp:Dir changing..."
#define BF_DICT_FTP_NOTREADY	"ftp_panel not ready"
#define BF_DICT_FTP_DIRRELOADING	"Ftp:Dir reloading..."
#define BF_DICT_MENU_COLSMODE	"Cols Mode"
#define BF_DICT_FTP_BKM_ASKDEL	"Delete this bookmark ?"
#define BF_DICT_FTP_RELOADFOLDER	"Reload folder"
#define BF_DICT_FTP_TASKDOWNLOAD	"download from ftp"
#define BF_DICT_FTP_TASKDEL	"delete file(s) from ftp"
#define BF_DICT_FTP_ERRGETNAME	"Can`t get name of current dir"
#define BF_DICT_FTP_ERRCONNECT	"Couldn't connect"
#define BF_DICT_ROSTER_OFF	" of "
#define BF_DICT_ROSTER_INFO	"Info"
#define BF_DICT_OWERWRITEALL	"Owerwrite all"
#define BF_DICT_MENU_PANELSETUP	"Panel setup..."
#define BF_DICT_SKIPALLERRORS	"Skip all errors"
#define BF_DICT_APPEND	"Append"
#define BF_DICT_ROSTER_COPYASK	"Copy question"
#define BF_DICT_ROSTER_FILE	"file "
#define BF_DICT_ROSTER_EXISTS	" exists"
#define BF_DICT_ROSTER_PREPARING	"preparing to process"
#define BF_DICT_ROSTER_PAUSED	" PAUSED "
#define BF_DICT_ROSTER_TOTAL	"total"
#define BF_DICT_ROSTER_TITLE	"File operations"
#define BF_DICT_ROSTER_PAUSERUN	"Pause/Run"
#define BF_DICT_MENU_SEARCH	"Search..."
#define BF_DICT_ROSTER_MINIMISE	"Minimize[Esc]"
#define BF_DICT_PAL_LOAD	"Load palete"
#define BF_DICT_PAL_SAVE	"Save palete"
#define BF_DICT_PAL_FILENAME	"File name:"
#define BF_DICT_ROSTER_OPERPROGRESS	"operations progress"
#define BF_DICT_TEXTVIEWER_SEARCH_DLG	"Search text"
#define BF_DICT_TEXTVIEWER_SEARCH_DLGTEXT	"Text:"
#define BF_DICT_MENU_CHANGECASE	"Change case..."
#define BF_DICT_MENU_TRACKER_ADDONS	"Tracker Add-Ons"
#define BF_DICT_TOPMENU_RIGHT	"Right"
#define BF_DICT_MENU_SHOWINFO	"Show info"
#define BF_DICT_MENU_SETOPPATH	"Set opposite path to my"
#define BF_DICT_MENU_GOTO	"Go to..."
#define BF_DICT_MENU_REFRESH	"Refresh"
#define BF_DICT_MENU_SHOWATTRS	"Show attributes..."
#define BF_DICT_MENU_MAKESHLINK	"Make SH-link..."
#define BF_DICT_PANEL_COL_NAME	"Name"
#define BF_DICT_PANEL_COL_TYPE	"Type"
#define BF_DICT_PANEL_COL_SIZE	"Size"
#define BF_DICT_PANEL_COL_DATE	"Date"
#define BF_DICT_TOPMENU_COMMON_MAINSETUP	"Main setup..."
#define BF_DICT_PANEL_BYTESIN	" bytes in "
#define BF_DICT_PANEL_FILES	" files "
#define BF_DICT_TOPMENU_COMMON_SELECTDICT	"Select language"
#define BF_DICT_SELDICT_TITLE	"Select dictionary_file"
#define BF_DICT_TEXTVIEWER_POS	"pos"
#define BF_DICT_TEXTVIEWER_COL	"col"
#define BF_DICT_TEXTVIEWER_CP	"cp"
#define BF_DICT_TEXTVIEWER_SHOWSPEC	"ShowSpec"
#define BF_DICT_TEXTVIEWER_HIDESPEC	"HideSpec"
#define BF_DICT_TEXTVIEWER_NEXT	"Next"
#define BF_DICT_TOPMENU_COMMON_EMPTY_TRASH	"Empty trash"
#define BF_DICT_TEXTVIEWER_CLOSE	"Close"
#define BF_DICT_TEXTVIEWER_CODEPAGE	"Code page"
#define BF_DICT_SEARCH	"Search"
#define BF_DICT_FILE	"file"
#define BF_DICT_FILESEARCH_FILENAME	"File name"
#define BF_DICT_FILESEARCH_BYTEXT	"By text"
#define BF_DICT_FILESEARCH_FROMCURFOLDER	"from current folder"
#define BF_DICT_FILESEARCH_ONVOLUMES	"on Volumes (use Ins for select)"
#define BF_DICT_NAME	"Name"
#define BF_DICT_FILESEARCH_SIZETYPE	"Size/Type"
#define BF_DICT_TOPMENU_COMMON_COMPARE	"Compare folders"
#define BF_DICT_FILESEARCH_PROGRESS	"Search in progress..."
#define BF_DICT_GOTO	"Go to"
#define BF_DICT_DIR	"Dir"
#define BF_DICT_FILESEARCH_FOUNDED	"Searching finished. Founded"
#define BF_DICT_FILESEARCH_FILES	"files"
#define BF_DICT_TYPE	"Type"
#define BF_DICT_VALUE	"Value"
#define BF_DICT_ERROR	"Error"
#define BF_DICT_ATTRDLG_OPENERROR	"can`t open file; error :"
#define BF_DICT_ATTRDLG_TITLE	"File attributes"
#define BF_DICT_TOPMENU_COMMON_SAVE_SETUP	"Save setup"
#define BF_DICT_CLOSE	"Close"
#define BF_DICT_MAINSETUP	"Main setup"
#define BF_DICT_MAINSETUP_COLSFONTS	"Colors and fonts"
#define BF_DICT_MAINSETUP_FILES	"File operations setup"
#define BF_DICT_MAINSETUP_DEBUG	"Debug setup"
#define BF_DICT_FONTSETUP_ANTI	"Anti aliasing"
#define BF_DICT_SIZE	"Size"
#define BF_DICT_FONTSETUP_FONTPANEL	"Font : Panel"
#define BF_DICT_FONTSETUP_FONTDIALOG	"Font : Dialog"
#define BF_DICT_TOPMENU_COMMON_LOAD_SETUP	"Load setup"
#define BF_DICT_FONTSETUP_FONTMONO	"Font : Mono"
#define BF_DICT_FONTSETUP_FONTCOMMAND	"Font : Command prompt"
#define BF_DICT_FONTSETUP_FLAGS	"Flags"
#define BF_DICT_MAINSETUP_ASKEXIT	"Ask before exit"
#define BF_DICT_MAINSETUP_VOLSHOWHOME	"Vol.dialog: show home,desktop,boot"
#define BF_DICT_MAINSETUP_VOLSTACK	"Vol.dialog: show folder-stack"
#define BF_DICT_MAINSETUP_VOLICONS	"Vol.dialog: show icons"
#define BF_DICT_MAINSETUP_PATHICON	"Panel: show path_icon"
#define BF_DICT_MAINSETUP_PANBACK	"Panel: use backspace"
#define BF_DICT_MAINSETUP_PANRET	"Panel: return to current folder"
#define BF_DICT_TOPMENU_COMMON_DEFAULT_SETUP	"Set setup to default"
#define BF_DICT_MAINSETUP_CMDPATH	"Command line : show path"
#define BF_DICT_MAINSETUP_TRACKADDICONS	"Tracker Add-Ons menu : show icons"
#define BF_DICT_MAINSETUP_SEARCHVOLICONS	"Search : setup : show volumes icons"
#define BF_DICT_MAINSETUP_AUTOSAVE	"Setup auto saving"
#define BF_DICT_SETUPFILES_SHOWDLG	"Taskdialog: show after new task"
#define BF_DICT_SETUPFILES_COPYDES	"Deselect after coping"
#define BF_DICT_SETUPFILES_MOVEDES	"Deselect after move"
#define BF_DICT_SETUPFILES_ASKDEL	"Ask before files deleting"
#define BF_DICT_SETUPFILES_ASKCOPY	"Ask before copy"
#define BF_DICT_FILES_LOADING	"Loading"

#endif // __BF_DICT_H__
